import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/global/Navbar";
import Footer from "@/components/global/Footer";
import QueryProvider from "@/components/api/QueryProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Product Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`dar ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full fixed z-[100] top-0">
          <Navbar />
        </div>
        <div className="w-full max-w-[1280px] mx-auto">

          <QueryProvider> {/* Step 3: Wrap children with QueryProvider */}
            {children}
          </QueryProvider>
        </div>
        <Footer />
      </body>
    </html>
  );
}
